---
- name: Install IntelliJ IDEA with desktop entry (hardened for Debian/Ubuntu/RHEL)
  hosts: lab_linux
  become: true
  become_method: sudo
  become_user: root
  gather_facts: yes

  vars:
    # ----- Choose edition and version -----
    # IU = Ultimate, IC = Community
    idea_edition: "IU"               # "IU" or "IC"
    idea_version: "2024.2.4"         # e.g., "2024.2.4"

    # Build URL (JetBrains direct tarball)
    intellij_filename: "idea{{ idea_edition }}-{{ idea_version }}.tar.gz"
    intellij_url: "https://download.jetbrains.com/idea/{{ intellij_filename }}"
    # Optional checksum (recommended): grab SHA256 from JetBrains and paste here
    intellij_sha256: ""  # e.g., "abc123..."

    # Install locations
    intellij_base_dir: "/opt"
    intellij_versioned_dir: "{{ intellij_base_dir }}/intellij-{{ idea_version }}"
    intellij_current_link: "{{ intellij_base_dir }}/intellij"
    intellij_archive_path: "/tmp/{{ intellij_filename }}"
    intellij_launcher_symlink: "/usr/local/bin/idea"

    # Desktop integration
    desktop_file_path: "/usr/share/applications/jetbrains-idea.desktop"
    icon_dest_path: "/usr/share/pixmaps/jetbrains-idea.png"

  pre_tasks:
    - name: Verify we are root (become working)
      command: id -u
      register: uid_check
      changed_when: false

    - name: Fail early if not root (enable privilege escalation in AWX/job)
      fail:
        msg: "Privilege escalation not active (uid={{ uid_check.stdout }}). Enable sudo/become."
      when: uid_check.stdout != '0'

    - name: Update apt cache (Debian/Ubuntu)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_facts.pkg_mgr == 'apt'

    # Debian/Ubuntu: ensure APT state files have sane perms (avoids mkstemp(13))
    - name: Ensure /var/lib/apt/extended_states exists with sane perms
      file:
        path: /var/lib/apt/extended_states
        state: touch
        owner: _apt
        group: root
        mode: '0644'
      when: ansible_facts.pkg_mgr == 'apt'

  tasks:
    # ---------- Base tools ----------
    - name: Ensure base tools on Debian/Ubuntu
      apt:
        name:
          - curl
          - tar
        state: present
      when: ansible_facts.os_family == 'Debian'

    - name: Ensure base tools on RHEL family
      yum:
        name:
          - curl
          - tar
        state: present
      when: ansible_facts.os_family == 'RedHat'

    # desktop-file-utils is nice-to-have; do not fail if missing
    - name: Install desktop-file-utils on Debian/Ubuntu (non-fatal)
      apt:
        name: desktop-file-utils
        state: present
      register: dfile_utils_deb
      failed_when: false
      when: ansible_facts.os_family == 'Debian'

    - name: Install desktop-file-utils on RHEL family (non-fatal)
      yum:
        name: desktop-file-utils
        state: present
      register: dfile_utils_rh
      failed_when: false
      when: ansible_facts.os_family == 'RedHat'

    # ---------- Download & Install IntelliJ ----------
    - name: Create /opt and parents
      file:
        path: "{{ intellij_base_dir }}"
        state: directory
        mode: '0755'

    - name: Download IntelliJ IDEA tarball
      get_url:
        url: "{{ intellij_url }}"
        dest: "{{ intellij_archive_path }}"
        mode: '0644'
        force: yes
        checksum: "{{ ('sha256:' + intellij_sha256) if intellij_sha256|length > 0 else omit }}"

    - name: Create versioned install dir
      file:
        path: "{{ intellij_versioned_dir }}"
        state: directory
        mode: '0755'

    - name: Extract IntelliJ to versioned directory
      unarchive:
        src: "{{ intellij_archive_path }}"
        dest: "{{ intellij_versioned_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Create/update stable /opt/intellij symlink to this version
      file:
        src: "{{ intellij_versioned_dir }}"
        dest: "{{ intellij_current_link }}"
        state: link
        force: yes

    - name: Create /usr/local/bin/idea launcher symlink
      file:
        src: "{{ intellij_current_link }}/bin/idea.sh"
        dest: "{{ intellij_launcher_symlink }}"
        state: link
        mode: '0755'
        force: yes

    - name: Install IntelliJ icon to system pixmaps
      copy:
        src: "{{ intellij_current_link }}/bin/idea.png"
        dest: "{{ icon_dest_path }}"
        remote_src: yes
        mode: '0644'

    - name: Create IntelliJ desktop entry
      copy:
        dest: "{{ desktop_file_path }}"
        mode: '0644'
        content: |
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=IntelliJ IDEA {{ 'Ultimate' if idea_edition == 'IU' else 'Community' }}
          Comment=Capable & ergonomic IDE for JVM/Android (JetBrains)
          Exec={{ intellij_launcher_symlink }} %f
          Icon={{ icon_dest_path }}
          Terminal=false
          Categories=Development;IDE;Java;
          StartupNotify=true
          StartupWMClass=jetbrains-idea
          MimeType=text/x-java;text/x-groovy;text/x-kotlin;application/x-java-archive;
          X-Desktop-File-Install-Version=0.26

    - name: Update desktop database if available (non-fatal)
      command: update-desktop-database
      register: desktopdb
      changed_when: "'updated' in (desktopdb.stderr | default('')) or 'updated' in (desktopdb.stdout | default(''))"
      failed_when: false

    - name: Show install summary
      debug:
        msg:
          - "IntelliJ {{ 'Ultimate' if idea_edition == 'IU' else 'Community' }} {{ idea_version }} installed to: {{ intellij_versioned_dir }}"
          - "Stable symlink: {{ intellij_current_link }}"
          - "Launcher: {{ intellij_launcher_symlink }}"
          - "Desktop entry: {{ desktop_file_path }}"
          - "Icon: {{ icon_dest_path }}"
          - "desktop-file-utils (Debian): rc={{ dfile_utils_deb.rc | default('n/a') }}, (RHEL): rc={{ dfile_utils_rh.rc | default('n/a') }}"
